import type { ParsedSkill, ParsedCommand } from '../types/index.js';
import { generateSkillsSection, generateCommandsSection } from './section-generator.js';

/**
 * Generate export file content with skills and commands.
 * Includes a header comment indicating the content is generated
 * and should be included in CLAUDE.md with @ syntax.
 *
 * Reuses existing section generators to ensure consistent formatting.
 */
export function generateExportContent(
  skills: ParsedSkill[],
  commands: ParsedCommand[]
): string {
  const parts: string[] = [];

  // Header comments
  parts.push('<!-- Generated by agent-compiler -->');
  parts.push('<!-- Add to CLAUDE.md with: @path/to/this/file.md -->');
  parts.push('');

  // Generate skills section if any skills provided
  const skillsSection = generateSkillsSection(skills);
  if (skillsSection) {
    parts.push(skillsSection);
  }

  // Add blank line between sections if both exist
  if (skillsSection && commands.length > 0) {
    parts.push('');
  }

  // Generate commands section if any commands provided
  const commandsSection = generateCommandsSection(commands);
  if (commandsSection) {
    parts.push(commandsSection);
  }

  // Join all parts, trim any trailing whitespace, and ensure single trailing newline
  return parts.join('\n').trim() + '\n';
}
