/**
 * Header comment for generated CLAUDE.md files
 */
export const TEMPLATE_HEADER_COMMENT = `<!-- Generated by Agent Compiler -->
<!-- This file embeds Claude Code skills and commands for reliable agent behavior -->
<!-- User content above the horizontal rule (---) is preserved on re-run -->`;

/**
 * Options for template generation
 */
export interface TemplateOptions {
  includeSkills: boolean;
  includeCommands: boolean;
}

/**
 * Generate a minimal template for a new CLAUDE.md file.
 * This template is ONLY used when the target file doesn't exist (ENOENT).
 * For existing files, user content is preserved as-is.
 *
 * Note: Template does NOT include section headings (## SKILLS, ## COMMANDS).
 * The merger will add those sections with actual content.
 * This prevents empty sections and ensures consistency with merge flow.
 */
export function generateTemplate(options: TemplateOptions): string {
  const parts: string[] = [];

  // Header comment
  parts.push(TEMPLATE_HEADER_COMMENT);
  parts.push('');

  // Default heading and placeholder
  parts.push('# CLAUDE');
  parts.push('');
  parts.push('[Add your project-specific instructions here]');

  // No separator or section headings - the merger will add those
  // when embedding skills/commands

  // Join with newlines and trim trailing whitespace
  return parts.join('\n').trimEnd();
}
