/**
 * Header comment for generated CLAUDE.md files
 */
export const TEMPLATE_HEADER_COMMENT = `<!-- Generated by Agent Compiler -->
<!-- This file embeds Claude Code skills and commands for reliable agent behavior -->
<!-- User content above the horizontal rule (---) is preserved on re-run -->`;

/**
 * Options for template generation
 */
export interface TemplateOptions {
  includeSkills: boolean;
  includeCommands: boolean;
}

/**
 * Generate a minimal template for a new CLAUDE.md file.
 * This template is ONLY used when the target file doesn't exist (ENOENT).
 * For existing files, user content is preserved as-is.
 */
export function generateTemplate(options: TemplateOptions): string {
  const parts: string[] = [];

  // Header comment
  parts.push(TEMPLATE_HEADER_COMMENT);
  parts.push('');

  // Default heading and placeholder
  parts.push('# CLAUDE');
  parts.push('');
  parts.push('[Add your project-specific instructions here]');
  parts.push('');

  // Separator
  parts.push('---');
  parts.push('');

  // Optional section headings
  if (options.includeSkills) {
    parts.push('## SKILLS');
    parts.push('');
  }

  if (options.includeCommands) {
    parts.push('## COMMANDS');
    parts.push('');
  }

  // Join with newlines and trim trailing whitespace
  return parts.join('\n').trimEnd();
}
